apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: bookstore-backend
  template:
    metadata:
      labels:
        app: bookstore-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: bookstore-db-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstore-db-secret
              key: POSTGRES_PASSWORD
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://bookstore-postgres:5432/{{ .Values.postgres.db }}"
